name: dikara_core
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  #  Core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.2
  firebase_crashlytics: ^3.3.7
  timezone: ^0.9.2

  #  Data Structure
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7

  #  Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.1

  #  Diagnostic
  fimber: ^0.7.0

  #  Network
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  retrofit: ^4.0.2
  http: ^1.1.0

  #  Routing
  auto_route: ^7.8.4

  #  Security
  encrypt: ^5.0.3

  #  State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  #  Storage
  shared_preferences: ^2.2.1

  #  UI
  animations: ^2.0.8
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0

  #  Utilities
  dartx: ^1.2.0
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  intl: ^0.18.1
  ios_utsname_ext: ^2.2.0
  logger: ^2.0.2+1
  ntp: ^2.0.0
  package_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build generator
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

  # Data Structure
  freezed: ^2.4.3
  json_serializable: ^6.7.1

  # Dependency Injection
  injectable_generator: ^2.4.0

  # Network
  retrofit_generator: ^8.0.0

  # Routing
  auto_route_generator: ^7.3.2

  flutter_lints: ^2.0.3

flutter:
  #  generate: true
  uses-material-design: true

  assets:
    - assets/icon/systems/
    - assets/lottie/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 700


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.dikara.dikara_core
    iosBundleIdentifier: com.dikara.dikaraCore
